version: '3.4'

services:
  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productapi2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
